version: '3.8'
services:
  web:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: group8
      DB_PASSWORD: 12345678

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: group8
      POSTGRES_PASSWORD: 12345678


    # Geen volumes meer
#    volumes:
#      - db_data:/var/lib/postgresql/data
#
#volumes:
#  db_data: